# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:41
from __future__ import unicode_literals

import apps.advertising.models
import apps.advertising.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=450)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Advertising',
                'verbose_name_plural': 'Advertising',
            },
        ),
        migrations.CreateModel(
            name='ImageAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=apps.advertising.models.ImageAdvertising.generate_path, validators=[apps.advertising.validators.valid_extension], verbose_name='Foto')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertising.Advertising')),
            ],
        ),
    ]
