# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20160525_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='timeout',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
