# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 13:45
from __future__ import unicode_literals

import apps.advertising.models
import apps.advertising.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_advertising_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='id_advertising',
            field=models.CharField(default=datetime.datetime(2016, 6, 9, 13, 45, 41, 14036, tzinfo=utc), max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertising',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='timeout',
            field=models.PositiveIntegerField(default=0, help_text='The input value is in seconds'),
        ),
        migrations.AlterField(
            model_name='imageadvertising',
            name='photo',
            field=models.FileField(upload_to=apps.advertising.models.ImageAdvertising.generate_path, validators=[apps.advertising.validators.valid_extension], verbose_name='Photo'),
        ),
    ]
